include/meltpooldg/advection_diffusion/advection_diffusion_operation.hpp, include/meltpooldg/advection_diffusion/advection_diffusion_operator.hpp, include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp, include/meltpooldg/curvature/curvature_operation.hpp, include/meltpooldg/curvature/curvature_operator.hpp, include/meltpooldg/interface/operator_base.hpp, include/meltpooldg/interface/scratch_data.hpp, include/meltpooldg/level_set/level_set_operation.hpp, include/meltpooldg/level_set/level_set_problem.hpp, include/meltpooldg/normal_vector/normal_vector_operation.hpp, include/meltpooldg/normal_vector/normal_vector_operator.hpp, include/meltpooldg/reinitialization/olsson_operator.hpp, include/meltpooldg/reinitialization/reinitialization_operation.hpp, include/meltpooldg/reinitialization/reinitialization_problem.hpp, include/meltpooldg/simulations/reinit_circle/reinit_circle.json, include/meltpooldg/simulations/reinit_circle_amr/reinit_circle_amr.json, include/meltpooldg/simulations/rotating_bubble/rotating_bubble.json
This framework should replace the template parameter `comp` and should fix issue #24. In the version of this PR, the `initialize`- functions obtain the additional arguments for selecting the current `DoFHandler`, `Quadrature`, etc. (`dof_idx`, `quad_idx`). Since the `initialize` functions should be designed in a compact way, I will think about finding a more elegant solution than simply extending the function argument list.
=> Remove template paramter comp 

include/meltpooldg/flow/adaflo_wrapper.hpp, include/meltpooldg/flow/adaflo_wrapper_parameters.hpp, include/meltpooldg/flow/flow_base.hpp, include/meltpooldg/flow/two_phase_flow_problem.hpp, include/meltpooldg/level_set/level_set_operation.hpp
This PR adds `TwoPhaseFlowProblem::update_phases()` and `TwoPhaseFlowProblem::compute_gravity_force()`. The places for the integration is probably not optimal (and is not what we have discussed) but I was not able to come up quickly with a better way (due to annoying dependencies of the computations). 
Let's clean up these functions once we need more complicated viscosity and density definitions.
=> Adaflo integration: update phases and compute gravity force

include/meltpooldg/flow/adaflo_wrapper.hpp
This is the guilty guy:
https://github.com/MeltPoolDG/MeltPoolDG/blob/b67627f8a620232d1c92d5340aa56dda7bb7dbb9/include/meltpooldg/flow/two_phase_flow_problem.hpp#L190
We should get the constraint matrix from `NavierStokes` as proposed by #58:
https://github.com/MeltPoolDG/MeltPoolDG/blob/b33a2d67b6ef416e83419bcbf352272e925f3337/include/meltpooldg/flow/adaflo_wrapper.hpp#L82
... not yet there ;)
=> "Fix" convergence issue

include/meltpooldg/flow/adaflo_wrapper.hpp, include/meltpooldg/flow/two_phase_flow_problem.hpp, include/meltpooldg/interface/parameters.hpp, include/meltpooldg/interface/scratch_data.hpp, include/meltpooldg/simulations/rising_bubble/rising_bubble.hpp
This PR allows us to have direct access to `NavierStokesinitialize_matrix_free()`.
=> Reuse MatrixFree in NavierStokes and enable simplices

include/meltpooldg/simulations/spurious_currents/spurious_currents.json
This PR fixes the level set degree in the input file of the spurious currents example.
@peterrum I will definitely address a "proper" choice of the degree parameter in a follow-up PR.
@JPmoep FYI
=> fix wrong degree in spurious currents input

include/meltpooldg/interface/parameters.hpp, include/meltpooldg/level_set/level_set_operation.hpp, include/meltpooldg/reinitialization/reinitialization_operation_adaflo_wrapper.hpp, include/meltpooldg/simulations/spurious_currents/spurious_currents.hpp, include/meltpooldg/utilities/postprocessor.hpp, include/meltpooldg/utilities/timeiterator.hpp
This PR improves the spurious currents simulation by computing the initial smooth level set field from the analytical solution of the reinitialization. An additional parameter `ls n initial reinit steps` is introduced that enables to control the number of initial reinitialization steps.
=> Fix spurious currents

include/meltpooldg/heat/heat_transfer_operation.hpp, include/meltpooldg/heat/heat_transfer_operator.hpp, include/meltpooldg/heat/heat_transfer_problem.hpp, include/meltpooldg/interface/fieldconditions.hpp, include/meltpooldg/interface/parameters.hpp, include/meltpooldg/interface/simulationbase.hpp, include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer.hpp, include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer_with_velocity.json, tests/unidirectional_heat_transfer_with_velocity.json
This PR moves the velocity vector to the heat problem. The heat operation and operator get a pointer to that vector. If the pointer is a nullptr the velocity terms are ignored.
Also, the velocity field function is now handled by the field conditions map.
=> Heat transfer: pass velocity with pointer

include/meltpooldg/flow/two_phase_flow_problem.hpp, include/meltpooldg/heat/laser.hpp, include/meltpooldg/heat/laser_heat_source_gusarov.hpp, include/meltpooldg/interface/parameters.hpp, include/meltpooldg/interface/problem_selector.hpp, include/meltpooldg/melt_pool/melt_pool_operation.hpp
This PR includes:
- add `two_phase_flow_with_heat_transfer` problem; If this problem type is chosen, a `HeatTransferOperation` is instantiated in the `TwoPhaseFlowProblem`.
- option enabled for solving a heat problem in case of a melt pool problem
- `compute_liquid_and_solid_phases`: liquid and solid regions are now distinguished based on the level set value and the temperature value.
Due to the numerous extensions available in the `TwoPhaseFlowProblem` it is currently a "mess". We should definitely discuss to split it up in separate operations, i.e. two-phase-flow, two-phase-flow with phase change, to maintain a clear coding structure.
=> Couple two phase flow with heat transfer

include/meltpooldg/heat/heat_transfer_operation.hpp, include/meltpooldg/heat/heat_transfer_operator.hpp, include/meltpooldg/heat/heat_transfer_problem.hpp, include/meltpooldg/interface/parameters.hpp, include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer_with_two_phase.json, tests/unidirectional_heat_transfer_with_two_phase.json
This PR introduces a two-phase material parameter input section for heat transfer. This material parameter section can be expanded for more material parameters in other physical contexts.
@mschreter what do you think of this design? If we always use the material section to define materials we can remove the material_data pointer and pass this struct by reference instead.
This might create a merge conflict with #106. I'll rebase whatever is merged last.
=> Add two-phase material parameter input for heat transfer

include/meltpooldg/utilities/utilityfunctions.hpp, unit_tests/merge_two_level_set_fields.cc, unit_tests/merge_two_level_set_fields.mpirun=4.output
This PR introduces the utility function to merge two level set fields based on boolean algebra (and solves Issue #108). The following cases are supported:
- intersection
- difference 
- union
=> Utility function for merging two level set fields

include/meltpooldg/simulations/thermo_capillary_two_droplets/thermo_capillary_two_droplets_parameters.ipynb
This PR add a jupyter notebook for determining the concrete parameters from the dimensionless problem definition of the two thermo-capillary droplets simulation. For some parameters one must still choose arbitrary values.
Fyi @mschreter
=> Add jupyter notebook for two droplet simualtion parameters

include/meltpooldg/flow/two_phase_flow_problem.hpp
This PR enables temperature-dependent surface tension also for melt pool simulations. A first result:
=> Activate temperature-dependent surface tension for melt pool simulations

include/meltpooldg/heat/heat_transfer_operation.hpp, include/meltpooldg/interface/parameters.hpp
... only a "minifix". I'll merge once CI is happy. @nmuch FYI: `AMGReduced` should now work without the exception. ~~However, I got into troubles when using `AMG` or `AMGReduced` together with AMR. I obtain the following stacktrace:~~
```bash
Stacktrace:
-----------
#0  /home/magdalena/TUM/build-deal/lib/libdeal_II.g.so.9.3.0-pre: dealii::TrilinosWrappers::SparseMatrix::add(unsigned int, unsigned int, unsigned int const*, double const*, bool, bool)
#1  /home/magdalena/TUM/build-deal/lib/libdeal_II.g.so.9.3.0-pre: void dealii::AffineConstraints<double>::distribute_local_to_global<dealii::TrilinosWrappers::SparseMatrix, dealii::Vector<double> >(dealii::FullMatrix<double> const&, dealii::Vector<double> const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, …
```
=> Fix AMGReduced

include/meltpooldg/advection_diffusion/advection_diffusion_adaflo_wrapper.hpp, include/meltpooldg/advection_diffusion/advection_diffusion_operation.hpp, include/meltpooldg/level_set/level_set_operation.hpp, include/meltpooldg/reinitialization/reinitialization_operation.hpp, include/meltpooldg/reinitialization/reinitialization_operation_adaflo_wrapper.hpp
... as a preparation of #152. In a follow-up PR, I would like to remove the direct usage of `DataOut`.
=> Do not use DataOut::attach_dof_handler()

include/meltpooldg/advection_diffusion/advection_diffusion_adaflo_wrapper.hpp, include/meltpooldg/advection_diffusion/advection_diffusion_operation.hpp, include/meltpooldg/advection_diffusion/advection_diffusion_operation_base.hpp, include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp, include/meltpooldg/evaporation/evaporation_operation.hpp, include/meltpooldg/flow/adaflo_wrapper.hpp, include/meltpooldg/flow/flow_base.hpp, include/meltpooldg/flow/two_phase_flow_problem.hpp, include/meltpooldg/heat/heat_transfer_operation.hpp, include/meltpooldg/heat/heat_transfer_problem.hpp, include/meltpooldg/interface/scratch_data.hpp, include/meltpooldg/level_set/level_set_operation.hpp, include/meltpooldg/level_set/level_set_problem.hpp, include/meltpooldg/melt_pool/melt_pool_operation.hpp, include/meltpooldg/reinitialization/reinitialization_operation.hpp, include/meltpooldg/reinitialization/reinitialization_operation_adaflo_wrapper.hpp, include/meltpooldg/reinitialization/reinitialization_operation_base.hpp, include/meltpooldg/reinitialization/reinitialization_problem.hpp, include/meltpooldg/utilities/postprocessor.hpp
This is how far as I was able to come till now. Since I will have time to continue the earliest in the late afternoon, I would suggest to merge and I will add the actual `GenericDataOut` implementation and the conversion function (`GenericDataOut` -> `DataOut`) then!
References #152.
=> Introduce alias GenericDataOut

include/meltpooldg/utilities/newton_raphson_solver.hpp, tests/solidification_slab.output, tests/tests_not_robust/film_boiling.with_adaflo_support=on.mpirun=4.output, tests/thermo_capillary_droplet.with_adaflo_support=on.mpirun=4.output, tests/thermo_capillary_two_droplets.with_adaflo_support=on.mpirun=4.output, tests/unidirectional_heat_transfer.mpirun=4.output, tests/unidirectional_heat_transfer_with_convection.mpirun=4.output, tests/unidirectional_heat_transfer_with_radiation.mpirun=4.output, tests/unidirectional_heat_transfer_with_radiation_and_convection.mpirun=4.output, tests/unidirectional_heat_transfer_with_radiation_and_convection_amr.mpirun=4.output, tests/unidirectional_heat_transfer_with_two_phase.mpirun=4.output, tests/unidirectional_heat_transfer_with_velocity.mpirun=4.output, tests/unidirectional_heat_transfer_with_velocity_and_solidification.output
This PR sets a fixed number of decimal places for the converged Newton steps. @nmuch: please recreate the output of the `solidification_slab.json` in #162 based on this PR.
=> Fix newton precision of converged step

include/meltpooldg/interface/scratch_data.hpp
references https://github.com/MeltPoolDG/MeltPoolDG/issues/151#issuecomment-845679323
This is from the "old days" when `MatrixFree` only accepted 1D quadrature rules.
=> Remove template argument dim_q from ScratchData

include/meltpooldg/heat/heat_transfer_operation.hpp, include/meltpooldg/heat/heat_transfer_operator.hpp, include/meltpooldg/simulations/solidification_slab/solidification_slab.json, include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer_with_velocity_and_solidification.json, include/meltpooldg/utilities/utilityfunctions.hpp, tests/solidification_slab.json, tests/solidification_slab.output, tests/unidirectional_heat_transfer_with_velocity_and_solidification.json
This PR fixes the heat equation for temperature dependent material parameters (during solidification). 
@mschreter When applying the mass balance assumption you sent me, a lot of terms cancel out.
With the consistent tangent the Newton shows quadratic convergence.
Also, in the mushy zone a cubic material parameter interpolation is used to have a continuous derivative. at the solidus and liquidus temperature.
=> Fix heat equation for temperature dependent params

include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp, include/meltpooldg/flow/two_phase_flow_problem.hpp, include/meltpooldg/heat/heat_transfer_problem.hpp, include/meltpooldg/interface/scratch_data.hpp, include/meltpooldg/interface/simulationbase.hpp, include/meltpooldg/level_set/level_set_problem.hpp, include/meltpooldg/reinitialization/reinitialization_problem.hpp, include/meltpooldg/simulations/advection_diffusion/advection_diffusion_user_output.hpp, include/meltpooldg/utilities/generic_data_out.hpp, include/meltpooldg/utilities/utilityfunctions.hpp, source/advection_diffusion/advection_diffusion_problem.cpp, source/evaporation/evaporation_operation.cpp, source/evaporation/evaporation_operation_marching_cube.cpp, source/flow/adaflo_wrapper.cpp, source/flow/two_phase_flow_problem.cpp, source/heat/heat_transfer_operator.cpp, source/heat/heat_transfer_problem.cpp, source/interface/scratch_data.cpp, source/level_set/level_set_problem.cpp, source/reinitialization/reinitialization_problem.cpp, source/simulations/simulation_selector.cpp, source/utilities/generic_data_out.cpp, source/utilities/postprocessor.cpp, tests/advection_diffusion_user_output.json, tests/advection_diffusion_user_output.mpirun=4.output
This PR references #152. @peterrum: If this is what you thought about, I'll continue by integrating the user output also in the other problems.
@nmuch: This way, output vectors are available in the `Simulation` files. The goal is to directly obtain e.g. a value over time in table form or any other postprocessed variable you are interested in. This should save us in certain cases from opening Paraview at all.
=> Draft for accessing result vectors

include/meltpooldg/heat/heat_transfer_operator.hpp, include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer.hpp, include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer_with_two_phase_and_solidification.json, include/meltpooldg/utilities/utilityfunctions.hpp, source/heat/heat_transfer_operator.cpp, tests/unidirectional_heat_transfer_with_two_phase_and_solidification.json, tests/unidirectional_heat_transfer_with_two_phase_and_solidification.output
This PR enables heat transfer with solidification and two-phase flow. 
The liquid's material are determined with the level-set function. On top of that, the solidification material parameters are determined consistently. I.e. if the temperature is below the liquidus temperature the liquid's parameters are interpolated with the solid's material parameters. If the temperature is below the solidus temperature, the material parameters equal the solid's material parameters regardless of the level-set.
In the heat_transfer_operator the material parameters can be determined with the new `get_material_parameters()`. The tangent cell loop required the temperature derivatives of the material parameters too, so there is `get_material_parameters_and_derivatives()` that determines the derivatives in …
=> Enable heat transfer with solidification and two-phase flow

include/meltpooldg/heat/laser_heat_source_gusarov.hpp, include/meltpooldg/interface/fieldconditions.hpp, include/meltpooldg/interface/parameters.hpp, include/meltpooldg/interface/simulationbase.hpp, include/meltpooldg/simulations/melt_front_propagation/melt_front_propagation.hpp, include/meltpooldg/simulations/melt_front_propagation/melt_front_propagation_static_gusarov.json, source/heat/heat_transfer_problem.cpp, source/heat/laser_heat_source_gusarov.cpp, source/interface/parameters.cpp, source/melt_pool/melt_pool_operation.cpp, source/simulations/simulation_selector.cpp, tests/melt_front_propagation_static_gusarov.json, tests/melt_front_propagation_static_gusarov.mpirun=4.output
This PR adds a simple melt front propagation simulation example: A solid piece of metal is heated with a laser heat source and melts. The solid and liquid phases have different thermal properties.
A couple of changes come with this addition:
- add user input for Gusarov laser
- restructure `LaserHeatSourceGusarov` so it can be used in a `dealii::Function`
- add a source field function and compute heat source vector
=> Melt front propagation

source/heat/heat_transfer_operator.cpp
This is a bug introduced in #162 and came up in #201.
=> Bugfix: Update ghost values of temperature_old in tangent operations of heat operator

include/meltpooldg/simulations/melt_front_propagation/melt_front_propagation_static_gusarov_amr.json, tests/melt_front_propagation_static_gusarov_amr.json, tests/melt_front_propagation_static_gusarov_amr.mpirun=4.output
Since I already worked on this we can benefit from the test case. #201, #203
=> Add simulation and test for melt front propagation with AMR

include/meltpooldg/evaporation/evaporation_model_base.hpp, include/meltpooldg/evaporation/evaporation_model_hardt_wondra.hpp, include/meltpooldg/evaporation/evaporation_model_recoil_pressure.hpp, include/meltpooldg/utilities/physical_constants.hpp, source/evaporation/evaporation_model_hardt_wondra.cpp, source/evaporation/evaporation_model_recoil_pressure.cpp, source/evaporation/evaporation_operation.cpp
This PR is part of a comprehensive refactoring (referencing #213) of the evaporation operations. It introduces an `EvaporationModelBase` class and derived classes. The interface to the actual `EvaporationOperation` is still work in progress.
=> Evaporation model refactor

include/meltpooldg/evaporation/evaporation_mass_flux_operator_base.hpp, include/meltpooldg/evaporation/evaporation_mass_flux_operator_continuous.hpp, include/meltpooldg/evaporation/evaporation_mass_flux_operator_interface_value.hpp, include/meltpooldg/evaporation/evaporation_model_base.hpp, include/meltpooldg/evaporation/evaporation_model_hardt_wondra.hpp, include/meltpooldg/evaporation/evaporation_model_recoil_pressure.hpp, include/meltpooldg/evaporation/evaporation_operation.hpp, include/meltpooldg/interface/parameters.hpp, include/meltpooldg/simulations/evaporating_droplet/evaporating_droplet_with_heat.json, include/meltpooldg/simulations/film_boiling/film_boiling_gibou_amr.json, include/meltpooldg/simulations/stefans_problem/stefans_problem1_with_flow_and_heat.json, include/meltpooldg/simulations/stefans_problem/stefans_problem1_with_flow_and_heat_1d.json, include/meltpooldg/simulations/stefans_problem/stefans_problem2_with_flow_and_heat_amr.json, source/evaporation/evaporation_mass_flux_operator_continous.cpp, source/evaporation/evaporation_mass_flux_operator_interface_value.cpp, source/evaporation/evaporation_model_hardt_wondra.cpp, source/evaporation/evaporation_model_recoil_pressure.cpp, source/evaporation/evaporation_operation.cpp, source/flow/two_phase_flow_problem.cpp, source/interface/parameters.cpp, tests/evaporating_droplet_with_heat.json, tests/stefans_problem1_with_flow_and_heat.json, tests/stefans_problem1_with_flow_and_heat_1d.json, tests/tests_not_robust/film_boiling.json, tests/tests_not_robust/stefans_problem2_with_flow_and_heat.json
This PR splits up the variants to fill the DoF vector for the evaporative mass flux:
- continuous over interface (`evaporation_mass_flux_operator_continuous.hpp`) --> take the value of mDot as it is
- interface value (`evaporation_mass_flux_operator_interface_value.hpp`) --> take the value of mDot at the interface and spread it across the interface
references #213
=> Refactor evaporative mass flux computation

source/advection_diffusion/advection_diffusion_operator.cpp, source/curvature/curvature_operator.cpp, source/evaporation/evaporation_operation.cpp, source/evaporation/evaporation_operation_marching_cube.cpp, source/flow/surface_tension_operation.cpp, source/flow/two_phase_flow_problem.cpp, source/heat/heat_transfer_operator.cpp, source/level_set/level_set_operator_with_phase_change.cpp, source/melt_pool/recoil_pressure_operation.cpp, source/normal_vector/normal_vector_operator.cpp, source/reinitialization/olsson_operator.cpp
"Noticed" while working on #223. I actually expected that these will give us trouble once `DEAL_II_DEPRECATED_EARLY` have been converted to `DEAL_II_DEPRECATED` directly after the deal.II release. But this did not happen, since we have forgot to add the `DEAL_II_DEPRECATED_EARLY` label. It has been fixed in https://github.com/dealii/dealii/pull/12350 so that the bools are available one more year...
=> Fix DEAL_II_DEPRECATED_EARLY stuff

include/meltpooldg/utilities/utilityfunctions.hpp, source/evaporation/evaporation_source_terms_continuous.cpp, source/evaporation/evaporation_source_terms_sharp.cpp, source/flow/adaflo_wrapper.cpp, source/heat/heat_transfer_operator.cpp, unit_tests/fill_dof_vector_from_cell_operation_vec_01.cc
I just wanted to keep this out of PR #229. ~Only the last commit is relevant.~
Pre C++17, one could accomplish the same with specialized template functions. In most cases, the language does not actually adds anything new but "improves" the syntax.
=> Introduce a single fill_dof_vector_from_cell_operation()

CMakeLists.txt, source/reinitialization/olsson_operator.cpp
~... depends on https://github.com/dealii/dealii/pull/12383.~
The reason for making this change is to be able to handle depredations as early as possible, however, the official Docker image is compiled without `DEAL_II_DEPRECATED_EARLY` enabled so that one needs to shift the responsibility to the user code.
=> Enable DEAL_II_DEPRECATED_EARLY per default

include/meltpooldg/heat/laser_heat_source_gusarov.hpp, include/meltpooldg/simulations/melt_front_propagation/melt_front_propagation.hpp, include/meltpooldg/simulations/melt_front_propagation/melt_front_propagation_static_gusarov.json, tests/melt_front_propagation_static_gusarov.json, tests/melt_front_propagation_static_gusarov.mpirun=4.output, tests/melt_front_propagation_static_gusarov_amr.mpirun=4.output
This PR fixes the domain of the melt front simulation, so that the laser heat soure acts opon the material correctly.
Fyi @mschreter
=> Fix melt front propagation laser direction

include/meltpooldg/heat/heat_transfer_operation.hpp, include/meltpooldg/heat/heat_transfer_problem.hpp, include/meltpooldg/heat/laser_heat_source_base.hpp, include/meltpooldg/heat/laser_heat_source_gauss.hpp, include/meltpooldg/heat/laser_heat_source_gusarov.hpp, include/meltpooldg/interface/parameters.hpp, include/meltpooldg/simulations/melt_front_propagation/melt_front_propagation.hpp, include/meltpooldg/simulations/melt_front_propagation/melt_front_propagation_static_interface_gauss.json, source/heat/heat_transfer_operation.cpp, source/heat/heat_transfer_problem.cpp, source/heat/laser.cpp, source/heat/laser_heat_source_gauss.cpp, source/heat/laser_heat_source_gusarov.cpp, source/interface/parameters.cpp, source/melt_pool/melt_pool_operation.cpp, tests/melt_front_propagation_static_gusarov.mpirun=4.output, tests/melt_front_propagation_static_gusarov_amr.mpirun=4.output, tests/melt_front_propagation_static_interface_gauss.json, tests/melt_front_propagation_static_interface_gauss.mpirun=4.output
This PR adds an alternative laser heat source impact model that only acts on the level-set interface. 
For the Gauss laser model this is implemented according to the SPH paper. 
The interface laser model is not compatible with the Gusarov laser model, so there is an assent. 
The laser heat source of any kind is now applied to the heat_source dof-vector by `HeatTransferProblem::run()`. 
A case and test has been added to the melt front propagation simulation, that includes a prescribed level-set. The domain has been expanded by a gaseous domain in positive dim-1 direction.
~~This PR includes #232. I'll rebase after #232 is merged.~~
=> Add interface laser heat source

simulations/melt_front_propagation/melt_front_propagation.hpp, simulations/melt_front_propagation/melt_front_propagation_moving_interface_gauss.json, simulations/melt_front_propagation/melt_front_propagation_static_gauss_amr.json, simulations/melt_front_propagation/melt_front_propagation_static_gusarov.json, simulations/melt_front_propagation/melt_front_propagation_static_gusarov_amr.json, simulations/melt_front_propagation/melt_front_propagation_static_interface_gauss.json, simulations/melt_front_propagation/melt_pool_tfi_static_interface_gauss.json, simulations/melt_front_propagation/melt_pool_tfi_static_interface_gauss_no_solidification.json, simulations/melt_front_propagation/melt_pool_tfi_static_interface_gauss_recoil_pressure.json, tests/melt_front_propagation_moving_interface_gauss.json, tests/melt_front_propagation_static_gusarov.json, tests/melt_front_propagation_static_gusarov_amr.json, tests/melt_front_propagation_static_interface_gauss.json, tests/melt_pool_tfi_static_interface_gauss.json, tests/melt_pool_tfi_static_interface_gauss_no_solidification.json
I'm working on a more complex simulation example and stared by generalizing the melt_front_propagation case. I noticed I need to define a several new boundary conditions and decided to create a new case instead of using melt_front_propagation... 
I thought we can use these additional parameters, anyway.
=> Add domain size and initial temperature param

include/meltpooldg/evaporation/evaporation_mass_flux_operator_thickness_integration.hpp, include/meltpooldg/utilities/utility_functions.hpp, source/evaporation/evaporation_mass_flux_operator_thickness_integration.cpp
This PR:
- computes multiplicity to evaluate the evaporative mass flux via thickness integration
- adds the check if a point is outside the bounding box within `generate_points_along_normal_vector`.
In the following picture we see the resulting evaporative mass flux. In this example periodic BC are applied between the right and the left face. This would mean that the values should be the same on the two faces, however they are not (on the right face they are exactly zero).
=> Introduce multiplicity in line integral

include/meltpooldg/melt_pool/melt_pool_operation.hpp, include/meltpooldg/melt_pool/melt_pool_problem.hpp, simulations/recoil_pressure/recoil_pressure.hpp, simulations/recoil_pressure/recoil_pressure_with_laser_fixed_solid_domain.json, source/melt_pool/melt_pool_operation.cpp, source/melt_pool/melt_pool_problem.cpp
This PR enables 
- `heat_transfer` BC in the recoil pressure example.
- the time-dependent update of zero velocity constraints in the solid phase. This can be enabled by setting 
```json
"mp set velocity to zero in solid": "true"
```
in the parameter file. The results looks now as follows for the coupled thermo-two-phase-flow melt pool problem (blue line marks the liquid domain):
@nmuch FYI
=> Enable time-dependent update of zero velocity constraints
