- include/meltpooldg/flow/adaflo_wrapper_parameters.hpp
- include/meltpooldg/simulations/rising_bubble/rising_bubble.json
This PR proposes to introduce a dedicated `adaflo` section within the `Navier-Stokes` section. Depends on https://github.com/kronbichler/adaflo/pull/6.
@mschreter What do you think?
> Move adaflo parameters into new section

- include/meltpooldg/interface/scratch_data.hpp
With https://github.com/dealii/dealii/pull/11168 being merged, we can simplify the code a bit.
> Simplify ScratchData::attach_quadrature

- include/meltpooldg/flow/two_phase_flow_problem.hpp
... related to https://github.com/dealii/dealii/pull/11183 and https://github.com/kronbichler/adaflo/pull/8.
> Replace n_macro_cells() with n_cell_batches

- include/meltpooldg/advection_diffusion/advection_diffusion_adaflo_wrapper.hpp
- include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp
setup_dof_system, initialize, refine_mesh
> Restructure AdvectionDiffusionProblem

- include/meltpooldg/reinitialization/reinitialization_problem.hpp
> Move code around in ReinitializationProblem

- include/meltpooldg/flow/two_phase_flow_problem.hpp
> TwoPhaseFlowProblem: move stuff around

- include/meltpooldg/utilities/vector_tools.hpp
This PR should fix issue #81. At the moment we are not using these utility functions.
> Fix Issue #81

- include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp
- include/meltpooldg/flow/adaflo_wrapper.hpp
- include/meltpooldg/flow/two_phase_flow_problem.hpp
- include/meltpooldg/level_set/level_set_problem.hpp
- include/meltpooldg/reinitialization/reinitialization_problem.hpp
- include/meltpooldg/simulations/advection_diffusion/advection_diffusion.hpp
- include/meltpooldg/simulations/reinit_circle/reinit_circle.hpp
- include/meltpooldg/simulations/stefans_problem/stefans_problem.hpp
- include/meltpooldg/simulations/stefans_problem/stefans_problem_with_flow.hpp
My first contribution for ages...
> Update deal.II: simplex folder and namespace

- CMakeLists.txt
- include/meltpooldg/flow/two_phase_flow_problem.hpp
- include/meltpooldg/interface/parameters.hpp
- include/meltpooldg/level_set/level_set_operator_with_phase_change.hpp
- tests/recoil_pressure.with_adaflo_support=on.mpirun=4.output
- tests/recoil_pressure_amr.with_adaflo_support=on.mpirun=4.output
- tests/recoil_pressure_fixed_solid_domain.with_adaflo_support=on.mpirun=4.output
- tests/recoil_pressure_simplex.with_simplex_support=on.with_adaflo_support=on.mpirun=4.output
This PR includes:
- fix melt pool with evaporation (no recoil pressure force is added in case of evaporation) 
- introduction of an additional case for computing the density in the interfacial region consistent with the mass balance
- update to C++20 standard
> Evapor additions melt pool

- .github/workflows/tests.yml
- include/meltpooldg/level_set/level_set_operator_with_phase_change.hpp
- include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer.hpp
... and turn warning to error in CI.
> Work on warnings

- include/meltpooldg/utilities/postprocessor.hpp
@nmuch: FYI
... already a long time overdue :-).
> Automatically create paraview output directory

- include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp
- include/meltpooldg/flow/two_phase_flow_problem.hpp
- include/meltpooldg/heat/heat_transfer_problem.hpp
- include/meltpooldg/interface/scratch_data.hpp
- include/meltpooldg/level_set/level_set_problem.hpp
- include/meltpooldg/reinitialization/reinitialization_problem.hpp
> Pass communicator to ScratchData

- include/meltpooldg/heat/heat_transfer_operator.hpp
Resolves #122.
The issue should be fixed with #12033. @nmuch Could you verify that this indeed works on your machine. Thanks!
> Enable MatrixFree-loop with vector update in HeatTransferOperator again

- .github/workflows/indentation.yml
- scripts/format-all
- scripts/format-all-code
- scripts/format-all-json
This PR introduces the following scripts:
```
scripts/format-all
scripts/format-all-code
scripts/format-all-json
```
and runs `scripts/format-all-json` in addition to the source code formatting check.
depends on #129
> Automatic formatting

- include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp
- include/meltpooldg/flow/two_phase_flow_problem.hpp
- include/meltpooldg/heat/heat_transfer_problem.hpp
- include/meltpooldg/level_set/level_set_problem.hpp
- include/meltpooldg/reinitialization/reinitialization_problem.hpp
- include/meltpooldg/utilities/postprocessor.hpp
This PR introduces the output of a `pvd`-file, enabling time-dependent (and not just time step dependent) output data. @nmuch @peterrum: FYI
> Introduce pvd file for time-dependent paraview data

- include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp
- include/meltpooldg/heat/heat_transfer_operation.hpp
- include/meltpooldg/heat/heat_transfer_problem.hpp
- tests/unidirectional_heat_transfer_with_radiation_and_convection_amr.json
- tests/unidirectional_heat_transfer_with_radiation_and_convection_amr.mpirun=4.output
This PR introduces AMR for the heat transfer problem based on the `KellyErrorEstimator`. @nmuch FYI
> Add AMR in heat transfer problem

- include/meltpooldg/heat/heat_transfer_operation.hpp
- include/meltpooldg/heat/heat_transfer_operator.hpp
... as discussed. I've tested AMG|AMGReduced|ILU|ILUReduced|Diagonal|DiagonalReduced and the number of iterations remain the same.
> Introduce local cell and boundary operations for tangent in heat_transfer_operator

- include/meltpooldg/heat/heat_transfer_operator.hpp
- include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer.hpp
- include/meltpooldg/simulations/unidirectional_heat_transfer/unidirectional_heat_transfer_with_velocity_and_solidification.json
- tests/unidirectional_heat_transfer_with_velocity_and_solidification.json
- tests/unidirectional_heat_transfer_with_velocity_and_solidification.output
The second order temperature derivative is zero for now but this will change in a follow-up.
> Add terms for convection with temperature-dependent material parameters to heat operator

- include/meltpooldg/utilities/postprocessor.hpp
references #152
This class should give us the flexibility to access vector by a simply providing the name. Magdalena could you take over from here and pass `GenericDataOut` somehow to the simulation classes. Thx!
> Implement GenericDataOut

- CMakeLists.txt
- include/meltpooldg/utilities/utilityfunctions.hpp
This PR enables also the built of a shared library and fixes a linking error in this case.
> Enable shared library build

- include/meltpooldg/evaporation/evaporation_operation_marching_cube.hpp
depends on https://github.com/dealii/dealii/pull/12245 and https://github.com/kronbichler/adaflo/pull/45
> Updates related to FEPointEvaluation

- include/meltpooldg/simulations/simulation_selector.hpp
- source/simulations/simulation_selector.cpp
> Precompile the simulations folder

- include/meltpooldg/advection_diffusion/advection_diffusion_adaflo_wrapper.hpp
- include/meltpooldg/advection_diffusion/advection_diffusion_operation.hpp
- include/meltpooldg/advection_diffusion/advection_diffusion_operator.hpp
- include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp
- source/advection_diffusion/advection_diffusion_adaflo_wrapper.cpp
- source/advection_diffusion/advection_diffusion_operation.cpp
- source/advection_diffusion/advection_diffusion_operator.cpp
- source/advection_diffusion/advection_diffusion_problem.cpp
> Precompile advection diffusion folder

- include/meltpooldg/curvature/curvature_operation.hpp
- include/meltpooldg/curvature/curvature_operation_adaflo_wrapper.hpp
- include/meltpooldg/curvature/curvature_operator.hpp
- source/curvature/curvature_operation.cpp
- source/curvature/curvature_operation_adaflo_wrapper.cpp
- source/curvature/curvature_operator.cpp
> Precompile curvature folder

- include/meltpooldg/level_set/level_set_operation.hpp
- include/meltpooldg/level_set/level_set_operator_with_phase_change.hpp
- include/meltpooldg/level_set/level_set_problem.hpp
- source/level_set/level_set_operation.cpp
- source/level_set/level_set_operator_with_phase_change.cpp
- source/level_set/level_set_problem.cpp
> Precompile level set folder

- include/meltpooldg/interface/problem_selector.hpp
- source/interface/problem_selector.cpp
references #151 
To speed up compilation, since plenty of stuff is compiled twice at the moment^^
> Split up ProblemSelector

- include/meltpooldg/evaporation/evaporation_operation.hpp
- include/meltpooldg/evaporation/evaporation_operation_marching_cube.hpp
- include/meltpooldg/melt_pool/melt_pool_operation.hpp
- include/meltpooldg/melt_pool/recoil_pressure_operation.hpp
- source/evaporation/evaporation_operation.cpp
- source/evaporation/evaporation_operation_marching_cube.cpp
- source/melt_pool/melt_pool_operation.cpp
- source/melt_pool/recoil_pressure_operation.cpp
> Precompile the evaporation and melt_pool folder

- include/meltpooldg/utilities/postprocessor.hpp
- source/utilities/postprocessor.cpp
> Precompile postprocessor

- include/meltpooldg/flow/two_phase_flow_problem.hpp
- include/meltpooldg/interface/parameters.hpp
- include/meltpooldg/interface/scratch_data.hpp
- include/meltpooldg/reinitialization/reinitialization_problem.hpp
- source/level_set/level_set_problem.cpp
- unit_tests/distance_function_rectangular_manifold.cc
- unit_tests/merge_two_level_set_fields.cc
references #151 
~I'll rebase once #180 is merged.~
> Use MeltPoolDG::ConditionalOStream

- include/meltpooldg/advection_diffusion/advection_diffusion_adaflo_wrapper.hpp
- include/meltpooldg/advection_diffusion/advection_diffusion_operation.hpp
- include/meltpooldg/advection_diffusion/advection_diffusion_operation_base.hpp
- include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp
- include/meltpooldg/evaporation/evaporation_operation.hpp
- include/meltpooldg/flow/adaflo_wrapper.hpp
- include/meltpooldg/flow/flow_base.hpp
- include/meltpooldg/heat/heat_transfer_operation.hpp
- include/meltpooldg/heat/heat_transfer_operator.hpp
- include/meltpooldg/interface/scratch_data.hpp
- include/meltpooldg/level_set/level_set_operation.hpp
- include/meltpooldg/level_set/level_set_operator_with_phase_change.hpp
- include/meltpooldg/level_set/level_set_problem.hpp
- include/meltpooldg/melt_pool/melt_pool_operation.hpp
- include/meltpooldg/reinitialization/reinitialization_operation.hpp
- include/meltpooldg/reinitialization/reinitialization_operation_adaflo_wrapper.hpp
- include/meltpooldg/reinitialization/reinitialization_operation_base.hpp
- include/meltpooldg/utilities/generic_data_out.hpp
- include/meltpooldg/utilities/postprocessor.hpp
- source/utilities/generic_data_out.cpp
- source/utilities/postprocessor.cpp
follow-up PR to #158 to reduce file dependencies
> Split up Postprocessor and GenericDataOut

- include/meltpooldg/interface/scratch_data.hpp
- source/interface/scratch_data.cpp
> Precompile scratch data

- include/meltpooldg/heat/heat_transfer_operation.hpp
- include/meltpooldg/heat/heat_transfer_operator.hpp
- include/meltpooldg/heat/heat_transfer_preconditioner.hpp
- include/meltpooldg/heat/heat_transfer_problem.hpp
- include/meltpooldg/heat/laser.hpp
- include/meltpooldg/heat/laser_heat_source_gusarov.hpp
- source/heat/heat_transfer_operation.cpp
- source/heat/heat_transfer_operator.cpp
- source/heat/heat_transfer_preconditioner.cpp
- source/heat/heat_transfer_problem.cpp
- source/heat/laser.cpp
- source/heat/laser_heat_source_gusarov.cpp
- source/melt_pool/melt_pool_operation.cpp
> Precompile heat folder

- include/meltpooldg/interface/scratch_data.hpp
- source/advection_diffusion/advection_diffusion_problem.cpp
- source/flow/adaflo_wrapper.cpp
- source/flow/two_phase_flow_problem.cpp
- source/heat/heat_transfer_problem.cpp
- source/interface/scratch_data.cpp
- source/level_set/level_set_problem.cpp
- source/reinitialization/reinitialization_problem.cpp
references #151 and closes #181
> Generalize ScratchData::attach_quadrature()

- source/flow/two_phase_flow_problem.cpp
- source/flow/two_phase_flow_problem_2.cpp
- source/flow/two_phase_flow_problem_3.cpp
- source/simulations/simulation_selector.cpp
- source/simulations/simulation_selector_2.cpp
- source/simulations/simulation_selector_3.cpp
references https://github.com/MeltPoolDG/MeltPoolDG/issues/151#issuecomment-845887778
> Split up two compilation units

- include/meltpooldg/evaporation/evaporation_operation.hpp
- include/meltpooldg/evaporation/evaporation_operation_marching_cube.hpp
- source/evaporation/evaporation_operation.cpp
- source/evaporation/evaporation_operation_marching_cube.cpp
notices while reviewing PR #192
> Minor clean up in EvaporationOperationMarchingCube

- include/meltpooldg/utilities/vector_tools.hpp
- source/advection_diffusion/advection_diffusion_adaflo_wrapper.cpp
- source/advection_diffusion/advection_diffusion_operation.cpp
- source/evaporation/evaporation_operation.cpp
- source/evaporation/evaporation_operation_marching_cube.cpp
- source/flow/adaflo_wrapper.cpp
- source/flow/surface_tension_operation.cpp
- source/flow/two_phase_flow_problem.cpp
- source/heat/heat_transfer_operator.cpp
- source/heat/laser.cpp
- source/level_set/level_set_operation.cpp
- source/level_set/level_set_operator_with_phase_change.cpp
- source/level_set/level_set_problem.cpp
- source/melt_pool/melt_pool_operation.cpp
- source/melt_pool/recoil_pressure_operation.cpp
- source/reinitialization/olsson_operator.cpp
- source/reinitialization/reinitialization_operation.cpp
- source/utilities/newton_raphson_solver.cpp
- unit_tests/merge_two_level_set_fields.cc
due to https://github.com/dealii/dealii/pull/12289
similar to https://github.com/kronbichler/adaflo/pull/46
> Fix deprecation warnings

- .github/workflows/nightly.yml
- README.md
> Add nightly test

- include/meltpooldg/simulations/stefans_problem/stefans_problem1_with_flow_and_heat.hpp
- include/meltpooldg/utilities/generic_data_out.hpp
- include/meltpooldg/utilities/utilityfunctions.hpp
- source/evaporation/evaporation_operation_marching_cube.cpp
- source/utilities/generic_data_out.cpp
This PR enables the direct output of data at level set zero for Stefan's problem 1 to a text file.
> Stefan's problem 1: tabular output of values at level set zero to file

- include/meltpooldg/simulations/thermo_capillary_droplet/thermo_capillary_droplet.hpp
- include/meltpooldg/simulations/thermo_capillary_droplet/thermo_capillary_droplet_3D.json
Here are the changes I made to run thermo-capillary droplet in 3D. Also I added the input file.
Fyi @mschreter
> Thermo-capillary droplet in 3D

- source/evaporation/evaporation_operation.cpp
... relate to https://github.com/dealii/dealii/pull/12332.
> Use VectorTools::point_value

- include/meltpooldg/simulations/film_boiling/film_boiling.hpp
As soon as I have results, I will add a GIF :-).
> Extend film boiling example for 3D

- include/meltpooldg/simulations/melt_front_propagation/melt_front_propagation_moving_interface_gauss.json
- source/interface/parameters.cpp
- tests/melt_front_propagation_moving_interface_gauss.json
- tests/melt_front_propagation_moving_interface_gauss.mpirun=4.output
@mschreter since you keep asking about with feature, I quickly tried it and found no issues 👍 
Here is a simulation and a test case.
> Add melt front propagation simulation with moving laser

- include/meltpooldg/flow/surface_tension_operation.hpp
- source/curvature/curvature_operator.cpp
- source/evaporation/evaporation_operation.cpp
- source/flow/surface_tension_operation.cpp
- source/reinitialization/olsson_operator.cpp
> Use new utility function to compute normal tolerance

- include/meltpooldg/interface/simulation_base.hpp
- source/advection_diffusion/advection_diffusion_problem.cpp
- source/flow/adaflo_wrapper.cpp
- source/flow/two_phase_flow_problem.cpp
- source/heat/heat_transfer_problem.cpp
- source/level_set/level_set_problem.cpp
- source/reinitialization/reinitialization_problem.cpp
> Resolve: Include Asserts for field functions into the simulation_base file

- include/meltpooldg/utilities/legacy.hpp
- simulations/stefans_problem/stefans_problem1_with_flow_and_heat.hpp
- source/evaporation/evaporation_mass_flux_operator_interface_value.cpp
- source/evaporation/evaporation_mass_flux_operator_thickness_integration.cpp
References #225.
At least it compiles. The `CellwiseInverseMassMatrix` operator is still missing. But nevertheless we could merge.
> Make compatible with deal.II 9.3 (part 1)

- source/advection_diffusion/advection_diffusion_adaflo_wrapper.cpp
- source/advection_diffusion/advection_diffusion_operation.cpp
- source/advection_diffusion/advection_diffusion_problem.cpp
- source/evaporation/evaporation_operation.cpp
- source/flow/adaflo_wrapper.cpp
- source/heat/heat_transfer_operation.cpp
- source/level_set/level_set_operation.cpp
- source/level_set/level_set_problem.cpp
- source/melt_pool/melt_pool_operation.cpp
- source/reinitialization/reinitialization_operation.cpp
- source/reinitialization/reinitialization_operation_adaflo_wrapper.cpp
possible since https://github.com/dealii/dealii/pull/11594 has been finally merged!
Hope I did not messed up anything...
> Remove not needed update_ghost_values()

- .github/workflows/tests.yml
- include/meltpooldg/utilities/legacy.hpp
- include/meltpooldg/utilities/utility_functions.hpp
- simulations/stefans_problem/stefans_problem1_with_flow_and_heat.hpp
- source/evaporation/evaporation_mass_flux_operator_interface_value.cpp
- source/evaporation/evaporation_mass_flux_operator_thickness_integration.cpp
> Make compatible with deal.II 9.3 (part 2)
